#!/bin/bash

# Workspaces
bspc monitor -d 1 2 3 4 5 6 7 8

# Config
bspc config border_radius 20
bspc config border_width 3
bspc config window_gap 10
bspc config split_ratio 0.50

bspc config focused_border_color "#FFDEDE" 
bspc config normal_border_color "#A3CBE7"
bspc config active_border_color "#B4E3AD"
bspc config presel_feedback_color "#E5A3A1"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config paddingless_monocle true
bspc config single_monocle false

# Rules
bspc rule -a feh state=floating
bspc rule -a sxiv state=floating
bspc rule -a mpv state=floating
bspc rule -a Conky state=floating
bspc rule -a stalonetray state=floating
bspc rule -a Lxappearance state=floating

# Autostart
$HOME/.config/sweetconfigs-xorg/bin/system/autostart
sxhkd -c $HOME/.config/bspwm/sxhkdrc &