#!/bin/bash

# Variable
alias bc='bspc config'
alias br='bspc rule'

# Workspaces
bspc monitor -d 1 2 3 4 5 6 7 8

# Config
bc border_width 1
bc window_gap 10
bc split_ratio 0.50
bc bottom_padding 0

bc config focused_border_color "#FFDEDE" 
bc config normal_border_color "#DEFBFF"
bc config active_border_color "#E4FFDE"
bc config presel_feedback_color "#FF8E8E"

bc borderless_monocle true
bc gapless_monocle false
bc focus_follows_pointer true
bc paddingless_monocle true
bc single_monocle false

# Rules
br -a feh state=floating
br -a sxiv state=floating
br -a mpv state=floating
br -a Conky state=floating
br -a stalonetray state=floating
br -a Lxappearance state=floating

sh $HOME/.config/bspwm/bin/programs &