[terminal]
  foot_config_file = '$HOME/.config/sweet-configs/terminals/foot/foot.ini'
  alacritty_config_file = '$HOME/.config/sweet-configs/terminals/alacritty/alacritty.yml'

  force_use_alacritty = false

  [terminal.custom]
    enable = true

    enable_x11 = false
    enable_wayland = true

    [terminal.custom.wayland]
      terminal = 'foot'
      config = '$HOME/.config/sweet-configs/terminals/foot/foot.ini'
      
      args = ['--title', 'SweetTerminal', '--config']
      float_args = ['--app_id', 'foot-floating']
      full_args = ['--app_id', 'foot-fullscreen', '--fullscreen']
      selector_args = ['-b', '1B1F23AA', '-c', 'FFDEDEFF', '-s', '00000000', '-w', '2', '-f', '%wx%h']

    [terminal.custom.x11]
      terminal = 'alacritty'
      config = '$HOME/.config/sweet-configs/terminals/alacritty/alacritty.yml'
      
      args = ['--title', 'SweetTerminal', '--config-file']
      float_args = ['--class', 'alacritty-floating']
      full_args = ['--class', 'alacritty-fullscreen']

[menu]
  app = 'wofi'
  
  terminal = 'foot'
  modi = 'run,ssh,drun,window,filebrowser'

    [menu.screenshot]
      directory = '$HOME/Pictures/Screenshots'
      
      config = '$HOME/.config/sweetconfigs/configs/menu/wofi/screenutils'
      style = '$HOME/.config/sweetconfigs-wayland/wofi/menu.css'
      colors = '$HOME/.config/sweetconfigs-wayland/wofi/colors'

      [menu.screenshot.icons]
        now = 'N'
        win = 'W'
        area = 'A'
        timer = 'T'

[location]
  auto_locate = false
  latitude = '35.6854'
  longitude = '139.7531'
  country = 'Japan'
  city = 'Tokyo'
  zip_code = '1638001'
  language = 'jp'

[weather]
  units = 'standard'

  [weather.icons]
    default = 'D'
    01d = 'D'
    01n = 'N'
    02d = 'D'
    02n = 'N'
    03d = 'D'
    03n = 'N'
    04d = 'D'
    04n = 'N'
    05d = 'D'
    05n = 'N'
    06d = 'D'
    06n = 'N'
    07d = 'D'
    07n = 'N'
    08d = 'D'
    08n = 'N'
    09d = 'D'
    09n = 'N'
    10d = 'D'
    10n = 'N'
    11d = 'D'
    11n = 'N'
    12d = 'D'
    12n = 'N'
    13d = 'D'
    13n = 'N'
    40d = 'D'
    50d = 'N'
  [weather.images]
    default = '$HOME/.config/eww/assets/01.jpg'
    01d = '$HOME/.config/eww/assets/01.jpg'
    01n = '$HOME/.config/eww/assets/01.jpg'
    02d = '$HOME/.config/eww/assets/01.jpg'
    02n = '$HOME/.config/eww/assets/01.jpg'
    03d = '$HOME/.config/eww/assets/01.jpg'
    03n = '$HOME/.config/eww/assets/01.jpg'
    04d = '$HOME/.config/eww/assets/01.jpg'
    04n = '$HOME/.config/eww/assets/01.jpg'
    05d = '$HOME/.config/eww/assets/01.jpg'
    05n = '$HOME/.config/eww/assets/01.jpg'
    06d = '$HOME/.config/eww/assets/01.jpg'
    06n = '$HOME/.config/eww/assets/01.jpg'
    07d = '$HOME/.config/eww/assets/01.jpg'
    07n = '$HOME/.config/eww/assets/01.jpg'
    08d = '$HOME/.config/eww/assets/01.jpg'
    08n = '$HOME/.config/eww/assets/01.jpg'
    09d = '$HOME/.config/eww/assets/01.jpg'
    09n = '$HOME/.config/eww/assets/01.jpg'
    10d = '$HOME/.config/eww/assets/01.jpg'
    10n = '$HOME/.config/eww/assets/01.jpg'
    11d = '$HOME/.config/eww/assets/01.jpg'
    12n = '$HOME/.config/eww/assets/01.jpg'
    12d = '$HOME/.config/eww/assets/01.jpg'
    13n = '$HOME/.config/eww/assets/01.jpg'
    13d = '$HOME/.config/eww/assets/01.jpg'
    40d = '$HOME/.config/eww/assets/01.jpg'
    50d = '$HOME/.config/eww/assets/01.jpg'