#!/usr/bin/env bash

# Warning: Do not delete or modify anything here unless you know what your doing

export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi

ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

leftwm-command "LoadTheme $SCRIPTPATH/theme.toml"

# Autostart
exec $HOME/.config/sweetconfigs-xorg/bin/system/autostart &