#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

## launch mako with alt config

CONFIG="$HOME/.config/hypr/mako/config"

if [[ ! `pidof mako` ]]; then
	mako --config ${CONFIG}
fi
