#!/bin/bash

cache="$HOME/.cache/calendar-widget.eww"
config="$HOME/Documents/Test/eww/Sweet"

run () {
	eww -c $config open calendar
	eww -c $config update calendar=true
}

if [[ ! `pidof eww` ]]; then
	eww -c $config daemon
	sleep 1
else
	if [[ ! -f "$cache" ]]; then
		touch "$cache"
		run
	else
		eww -c $config update calendar=false
		sleep 0.075
		eww -c $config close calendar
		rm "$cache"
	fi
fi
