#!/bin/bash

players=$(echo "playerctl -p spotify,%any,firefox,chromium,brave,mpd")
player_status=$($players status)
artist=$(playerctl metadata --format '{{ artist }}')
title=$(playerctl metadata --format '{{ title }}')
albumart="$($players metadata mpris:artUrl | sed -e 's/open.spotify.com/i.scdn.co/g')"
cache="$HOME/.cache/eww/music"

[ ! -d $cache ] && mkdir $cache

status_icon () {
    if [ "$player_status" = "Playing" ]; then
	    icon=""
    elif [ "$player_status" = "Paused" ]; then
	    icon=""
    else
	    icon=""
    fi

    echo $icon
}

status_value () {
	player_name=$(echo $(playerctl -l) | cut -d '.' -f 1)

	if [ "$player_status" = "Playing" ]; then
		echo "Now Playing - via ${player_name^}"
	else
		echo "Music"
	fi
}

title () {
    if [ -z "$title" ]; then
		echo "Nothing Playing";
	else
		echo $title
	fi
}

artist () {
    if [ "$title" = "Advertisement" ]; then
		echo "Spotify Free"
	else
		if [ -z "$artist" ]; then
			echo "Unknown Artist";
		else
			echo "by $artist"
		fi
	fi
}

cover () {
    cover="$cache/cover.png"
    fallback="$HOME/Documents/Test/eww/Bar/assets/fallback.png"

    [ $($players metadata mpris:artUrl) ] && curl -s "$albumart" --output $cover || cp $fallback $cover 
    echo $cover
}

cover_notification () {
    cover="$cache/$DUNST_SUMMARY.png"
    cache_file="$cache/temp.png"

    cover_url="$($players metadata mpris:artUrl | sed -e 's/open.spotify.com/i.scdn.co/g')"

    if [[ $($players metadata mpris:artUrl) ]]; then
	    curl -s "$cover_url" --output "$cache_file"
    fi

    cp "$cache_file" "$cover"
}

position () {
    position=$(playerctl position | sed 's/..\{6\}$//')
	duration=$(playerctl metadata mpris:length | sed 's/.\{6\}$//')
	
    if [[ $position -gt 0 ]]; then
	    printf "%0d:%02d" $((position%3600/60)) $((position%60))
	    printf " / "
	    printf "%0d:%02d" $((duration%3600/60)) $((duration%60))
    else
        echo " "
    fi
}

case $1 in
    next)
        $players next
    ;;
	previous)
        $players previous
    ;;
	toggle)
        $players play-pause
    ;;
    status)
        status_value
    ;;
    status-icon)
        status_icon
    ;;
    title)
        title
    ;;
    artist)
        artist
    ;;
    title-artist)
        echo $(title) - $(artist)
    ;;
    cover)
        cover
    ;;
    cover-notification)
        cover_notification
    ;;
    position)
        position || echo "--:-- / --:-- "
    ;;
esac