#!/bin/bash

do_not_disturb="$HOME/.cache/eww/do-not-disturb.eww"
config="$HOME/Documents/Test/eww/Sweet"

finish () {
	eww -c $config update notification=false; sleep 0.270
	eww -c $config close notification-popup
}

if [[ ! `pidof eww` ]]; then
	eww -c $config daemon
	sleep 1
else
	if [[ ! -f "$do_not_disturb" ]]; then
		killed=false
		for pid in $(pidof -x openEwwPopup.sh); do
			if [ $pid != $$ ]; then
				kill -9 $pid
				killed=true
			fi
		done >/dev/null

		if ! $killed; then
			sleep 0.5
			eww -c $config update notification=true
			eww -c $config open notification-popup
		fi

		sleep 5
		finish
		unset killed
	fi
fi