#!/bin/bash

brightness=$(brightnessctl i | grep -oP '\(\K[^%\)]+')
volume=$(pamixer --get-volume)
empty_battery="0"

volume_icon () {
    if [ $volume -lt "35" ]; then
        icon=""
    elif [ $volume -lt "70" ]; then
        icon=""
    else
        icon=""
    fi

    [ $(pamixer --get-mute) = "true" ] && icon=""

    echo $icon
}

brightness_icon () {
    if [ $brightness -lt "40" ]; then
        echo ""
    elif [ $brightness -lt "60" ]; then
        echo ""
    else
        echo ""
    fi
}

network_icon () {
    wifi_check=$(cat /sys/class/net/w*/operstate)
    ethernet_check=$(cat /sys/class/net/e*/operstate)

    
	if [ $wifi_check = up ]; then
        echo ""
    else
        if [ $ethernet_check = up ]; then
            echo ""
        else
            echo ""
        fi
    fi
}

network_speed () {
    interface="$(ip link | awk '/state UP/ {print $2}' | tr -d :)"

    received_1=$(cat /sys/class/net/$interface/statistics/rx_bytes)
    transmitted_1=$(cat /sys/class/net/$interface/statistics/tx_bytes)

    received_2=$(cat /sys/class/net/$interface/statistics/rx_bytes)
    transmitted_2=$(cat /sys/class/net/$interface/statistics/tx_bytes)

    bandwidth_up=`expr $transmitted_2 - $transmitted_1`
    bandwidth_down=`expr $received_2 - $received_1`

    upspeed=$(expr $bandwidth_up / 1024)
    downspeed=$(expr $bandwidth_down / 1024)

    echo "$downspeed kB/s $upspeed kB/s"
}

network_name () {
    ssid=$(iwgetid -r)
    if [ -z $ssid ]; then 
        echo "Not Connected"
    else 
        "Connected to $ssid"
    fi
}


battery_empty () {
    if [ "$empty_battery" -gt 0 ]; then
	    if [ ! -f "$HOME/.cache/empty_battery_capacity" ]; then 
            echo $(($RANDOM % 100)) > "$HOME/.cache/empty_battery_capacity"
        fi
    fi
}

battery_icon () {
    if [[ -d /sys/class/power_supply/ACAD ]]; then
		echo ""
	elif [[ -d /sys/class/power_supply/BAT ]]; then
		if [[ $(cat /sys/class/power_supply/BAT/status) == "Discharging" ]]; then
			echo ""
		else
			echo ""
		fi
	else
		echo ""
	fi
}

battery_capacity () {
    if [ "$empty_battery" -gt 0 ]; then
		if [ -f "$HOME/.cache/empty_battery_capacity" ]; then
			echo $(cat "$HOME/.cache/empty_battery_capacity")
		fi
	elif [ -f /sys/class/power_supply/BAT0/capacity ]; then
		echo $(cat /sys/class/power_supply/BAT0/capacity)
	fi
}

case $1 in
    volume-icon)
        volume_icon
    ;;
    brightness-icon)
        brightness_icon
    ;;
    volume-value)
        echo $volume
    ;;
    brightness-value)
        echo $brightness
    ;;
    network-icon)
        network_icon
    ;;
    network-speed)
        network_speed
    ;;
    network-name)
        network_name
    ;;
    network-menu)
        ~/.config/sweetconfigs-xorg/bin/rofi/network
    ;;
    empty-battery)
        battery_empty
    ;;
    battery-icon)
        battery_icon
    ;;
    battery-capacity)
        battery_capacity
    ;;
    power-menu)
        ~/.config/sweetconfigs-xorg/bin/rofi/power
    ;;
esac
