#!/bin/bash

[ ! -d $cache_dir ] && mkdir $cache_dir

cache_dir="$HOME/.cache/eww"
cache="$cache_dir/control-center.eww"
config="$HOME/Documents/Test/eww/Widgets-V4"
active_players=$(playerctl -l | head -n 1)

run () {
	eww -c $config open control-panel
	sleep 0.6
	eww -c $config update control-panel=true
	sleep 1 &&  [[ ! -z $active_players ]] && eww -c $config update music-panel=true
}

if [[ ! `pidof eww` ]]; then
	eww -c $config daemon
	sleep 1
else
	if [ ! -f $cache ]; then
		touch $cache
		run
	else
		[[ ! -z $active_players ]] && eww -c $config update music-panel=false && sleep 0.4
		eww -c $config update control-panel=false
		sleep 0.6
		eww -c $config close control-panel
		rm $cache
	fi
fi