#!/bin/bash
zscroll -l 20 \
        --delay 1 \
        --scroll-padding " | " \
        --match-command "./music title" \
        --match-text "Playing" "--scroll 1" \
        --match-text "Paused" "--scroll 0" \
        --update-check true "./music title" &
wait